### ISSUE TITLE
Missing final steps to run Python app

### ISSUE THREAD

**Issue by duanecr** [gloveboxes/Raspberry-Pi-Python-Environment-Monitor-with-the-Pimoroni-Enviro-Air-Quality-PMS5003-Sensor#1]
I followed the instructions and got to the end, but the final instructions are very vague about "Configure Python App for IoT Central".  It references the three pieces needed to connect to Azure IoT Central, but it doesn't say where to edit the settings or how to start the application to use those settings.  I guessed at updating the .env file as it looked appropriate.  I used the reference from the bottom of your tutorial for https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-connect-device-python.  I was able to figure out to run python3 main.py in the directory.  It just went back to the command prompt.  I am not a developer, but I was able to figure out that the main.py is where it needs the information.  I wasn't able to figure out how to get the main.py to read the .env for the environment variables.  I just edited the main.py file and put the variables in place of none and commented out the call for reading the variables externally.  Can you tell me how I would be able to read the .env file properly so I'm not editing the main.py?

**Comment by gloveboxes** [comment]
hey there - the labs are now completed.
